In [1]:
#pip install opencv-python

In [2]:
import cv2
import numpy as np

## Load/Read image

In [3]:
#Load an image 'imread' specifying the path of the image
img=cv2.imread('Modi.jpg',1)

**Let's Take a closer look at how images are stored**

In [4]:
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


**Shape gives the dimensions of the image array**

In [5]:
img.shape
#The 3D dimensions are 1358 pixels in height * 1500 pixels wude
#3 means that are 3 components (RGB) that make us this image

(1358, 1500, 3)

## Display the image

In [6]:
#to display our image variable , we use 'imshow'
#the first parameter will be title shown on image window
#the second parameter is the image variable
#img=cv2.imread('image_examples/Modi.jpg',0)
cv2.imshow('PM',img)

# 'waitKey' allows us to input information when a image window is open
# By leaving it blank it just waits for anykey to be pressed before continuing.
# how long you keep the window open (time is in milliseconds here)
cv2.waitKey(3000)

# this closes all open windows.
# Failure to place this will cause your program hang
cv2.destroyAllWindows()

## Save Image

In [7]:
cv2.imwrite('pm_bw.jpg',img)

True

## Resize Image

In [8]:
img=cv2.imread('Modi.jpg',1)
resized_img=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_img,cv2.COLOR_BGR2GRAY)
cv2.imshow('pm',gray)
cv2.waitKey(2000)
cv2.destroyAllWindows()

In [9]:
img.shape[0]*.5

679.0

In [10]:
img.shape[1]*0.5

750.0

In [11]:
cv2.__version__

'4.9.0'

In [12]:
import warnings
warnings.simplefilter('ignore')


## Face Detection using HAAR Cascade Classifiers

In [13]:
# we point OpenCV's CascadeClassifier function to where our classifier (XML file format)is stored
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# Load our image then convert it to grayscale
image=cv2.imread('Modi,jpg')
image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)

# Tuning Cascade Classifier - detectMulituScale(input image,**scalar factor**,**Min Neighbors**)
face=face_classifier.detectMultiScale(gray,1.05,5)
# scale factor -specifies how much we reduce the image size each time we scale.
# E.g. in face detection we typically use 1.3. This means we reduce the image by 30% each time it's size.
# smaller values, like 1.05 will take longer to compute , but will increase the rate of detection.
## Min Neighbors**
# specifies the number of neighbors each potential window should have in order to consider it a positive detection.
# Typically set between 3-6.
# It acts as sensitivity setting, low values will sometimes detect multiples faces over a single face.
# High values will ensure less false positives , but you may miss some faces.

In [14]:
print(face)

[[205  79 217 217]]


In [15]:
# we point OpenCV's CascadeClassifier function to where our classifier (XML file format)is stored
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
# Load our image then convert it to grayscale 
image=cv2.imread('Modi.jpg',1)
image=cv2.resize(image,(679,750))
gray=cv2.cvtColor(image,cv2.COLOR_BGR2GRAY)
# Tuning Cascade Classifier - detectMulituScale(input image,**scalar factor**,**Min Neighbors**)
faces=face_classifier.detectMultiScale(gray,1.05,5)
# scale factor -specifies how much we reduce the image size each time we scale.
# E.g. in face detection we typically use 1.3. This means we reduce the image by 30% each time it's size.
# smaller values, like 1.05 will take longer to compute , but will increase the rate of detection.
## Min Neighbors**
# specifies the number of neighbors each potential window should have in order to consider it a positive detection.
# Typically set between 3-6.
# It acts as sensitivity setting, low values will sometimes detect multiples faces over a single face.
# High values will ensure less false positives , but you may miss some faces.

# when no faces detected , face_classifier returns an empty tuple.
if faces is ():
    print('no face found.')
# we iterate through our faces array and draw a rectangle
# over each face in faces
for (x,y,h,w) in faces:
    cv2.rectangle(image,(x,y),(x+h,y+w),(165,125,255),5)
cv2.imshow('pm',image)
cv2.waitKey()
cv2.destroyAllWindows()

## Face & Eye Detection using HAAR Cascade Classifiers in image

In [16]:
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_classifier=cv2.CascadeClassifier('haarcascade_eye.xml')

img=cv2.imread('Modi.jpg',1)
resized_image=cv2.resize(img,(500,500))
gray=cv2.cvtColor(resized_image,cv2.COLOR_BGR2GRAY)

faces=face_classifier.detectMultiScale(gray,1.3,5)
# when no faces detected , face_classifier returns an empty tuple.
if faces is ():
    print('no face found.')
for (x,y,w,h) in faces:
    cv2.rectangle(resized_image,(x,y),(x+w,y+h),(255,0,0),5)
    roi_gray=gray[y:y+h,x:x+w]
    roi_color=resized_image[y:y+h,x:x+w]
    eyes=eye_classifier.detectMultiScale(roi_gray)
    for (ex,ey,ew,eh) in eyes:
        cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
cv2.imshow('img',resized_image)
cv2.waitKey()
cv2.destroyAllWindows()

## Capture a Video

In [17]:
# Doing some face Recognization with the webcam
import cv2
video=cv2.VideoCapture(0)
while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow('Video',gray)
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

## Face & Eye Detection using HAAR Cascade Classifiers 

In [18]:
# Defining a function that will do the detections
face_classifier=cv2.CascadeClassifier('haarcascade_frontalface_default.xml')
eye_classifier=cv2.CascadeClassifier('haarcascade_eye.xml')
def detect(gray,frame):
    faces=face_classifier.detectMultiScale(gray,1.3,5)
    for (x,y,w,h) in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),5)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_classifier.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame
# Doing some face recognization with the webcam
video=cv2.VideoCapture(0)
while True:
    check,frame=video.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    canvas=detect(gray,frame)
    cv2.imshow('Video',canvas)
    if cv2.waitKey(1) == ord('q'):
        break
video.release()
cv2.destroyAllWindows()

## Pedistrian Detection

In [19]:
import cv2
# Create our body classifier
body_classifier=cv2.CascadeClassifier('haarcascade_fullbody.xml')
#Initialize video capture for video file
cap=cv2.VideoCapture('walking.avi')
# Loop once video is successfully loaded
while cap.isOpened():
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    body=body_classifier.detectMultiScale(gray,1.2,3)
    # Extract bounding boxes for any bodies identified
    for x,y,w,h in body:
        cv2.rectangle(gray,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Pedestrains',gray)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

In [20]:
import time
# Create our body classifier
car_classifier=cv2.CascadeClassifier('haarcascade_car.xml')
#Initialize video capture for video file
cap=cv2.VideoCapture('cars.avi')
# Loop once video is successfully loaded
while cap.isOpened():
    time.sleep(0.05)
    # Read first frame
    check,frame=cap.read()
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    # Pass frame to our body classifier
    cars=car_classifier.detectMultiScale(gray,1.4,2)
    # Extract bounding boxes for any bodies identified
    for x,y,w,h in cars:
        cv2.rectangle(gray,(x,y),(x+w,y+h),(0,255,255),2)
        cv2.imshow('Pedestrains',gray)
    if cv2.waitKey(1)==ord('q'):
        break
cap.release()
cv2.destroyAllWindows()
    